ShoesStore/Areas/Admin/ViewModels/SanPhamViewModel.cs
using ShoesStore.Models;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ShoesStore.Areas.Admin.ViewModels
{
    public class SanPhamViewModel
    {
        public int DongsanphamId { get; set; }
        public string DongsanphamName { get; set; }
        public string TypeName {  get; set; }
        public enum TrangThaiEnum
        {
            [VietnameseName("Đang bán")]
            Dangban = 1,
            [VietnameseName("Ngưng bán")]
            NgungBan = 2,
            [VietnameseName("Hot")]
            Hot = 3,
            [VietnameseName("Mới nhất")]
            New = 4
        }

        public TrangThaiEnum TrangThai { get; set; }


        [Required(ErrorMessage = "Sản phẩm đã hết màu")]
        public string IdMau {  get; set; }
        public List<string> tenSize {  get; set; }
        public List<int> slton {  get; set; }

        [Required(ErrorMessage ="Vui lòng nộp ảnh đại diện")]
        [Display(Name = "Ảnh đại diện")]
        [NotMapped] //Dont save this image database,save in root
        public IFormFile AvatarImage { get; set; }

        [Required(ErrorMessage = "Vui lòng nộp ảnh mặt trên")]
        [Display(Name = "Ảnh mặt trên giày")]
        [NotMapped]
        public IFormFile TopImage { get; set; }

        [Required(ErrorMessage = "Vui lòng nộp ảnh mặt đế")]
        [Display(Name = "Ảnh mặt đế giày")]
        [NotMapped]
        public IFormFile BottomImage { get; set; }
        public IFormFile VideoFile { get; set; }
    }
}

ShoesStore/Models/Sanpham.cs
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ShoesStore.Models;

public partial class Sanpham
{
    public int Masp { get; set; }

    public int Madongsanpham { get; set; }

    public string Mamau { get; set; } = null!;

    public string Anhdaidien { get; set; } = null!;

    public string Anhmattren { get; set; } = null!;

    public string Anhdegiay { get; set; } = null!;

    public string? Video { get; set; }

    [JsonIgnore]
    public virtual Dongsanpham MadongsanphamNavigation { get; set; } = null!;
    [JsonIgnore]

    public virtual Mau MamauNavigation { get; set; } = null!;

    public virtual ICollection<Sanphamsize> Sanphamsizes { get; set; } = new List<Sanphamsize>();
    public enum TrangThaiEnum
    {
        DangBan = 1,
        NgungBan = 2,
        Hot = 3,
        New = 4
    }

    public TrangThaiEnum TrangThai { get; set; }
}

ShoesStore/ViewModels/SanphamViewModel.cs
using ShoesStore.Models;

namespace ShoesStore.ViewModels
{
	public class SanphamViewModel
	{
		public Dongsanpham dongsanpham {  get; set; }
		public List<Sanpham> sanphams { get; set; }
		public List<string> tenSize {  get; set; }
		public List<int> slton {  get; set; }
		
	}
}

ShoesStore/Controllers/SanPhamController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShoesStore.InterfaceRepositories;
using ShoesStore.Models;
using ShoesStore.ViewModels;
using System;
using System.Diagnostics;
using X.PagedList;

namespace ShoesStore.Controllers
{
	public class SanPhamController : Controller
	{
        IHttpContextAccessor httpcontextAcc; IBinhLuan blRepo;
		 IDongSanpham dongspRepo;ISanpham spRepo; IMau mauRepo; IKhachhang khRepo;
		public SanPhamController(ShoesDbContext context, IDongSanpham dongspRepo, ISanpham spRepo, IMau m,
			IHttpContextAccessor httpcontextAcc, IKhachhang khRepo,IBinhLuan blRepo)
		{
			this.dongspRepo = dongspRepo;
			this.spRepo = spRepo;
			this.mauRepo = m;
			this.httpcontextAcc = httpcontextAcc;
			this.khRepo = khRepo;
			this.blRepo = blRepo;
		}	
		public IActionResult SanPhamTheoLoai(string? searchString, string? maMau, int? sortGia, decimal? minPrice, decimal? maxPrice,int maLoai)
		{
			CreateData();

			ViewBag.maLoai = maLoai;
			ViewBag.sortGia1 = sortGia;
			ViewBag.maMau1 = maMau;
			ViewBag.searchString1 = searchString;
			ViewBag.minPrice1 = minPrice;
			ViewBag.maxPrice1 = maxPrice;
			TempData["AddCategoryId"] = "true";

			List<DongsanphamViewModel> dongspview = dongspRepo.GetDongspView(maMau,sortGia,searchString,minPrice,maxPrice,maLoai);

			if (IsAjaxRequest())
			{
				return PartialView("_PartialSanPhamTheoLoai", dongspview);
			}

			else
			{
				return View(dongspview);
			}
			
		}

		private bool IsAjaxRequest()
		{
			var request = httpcontextAcc.HttpContext.Request;
			return request.Headers["X-Requested-With"] == "XMLHttpRequest";
		}

		public IActionResult HienThiSanpham(int madongsanpham, int masp)
		{
			SanphamViewModel pDetail = spRepo.HienThiSanpham(madongsanpham, masp);
            HttpContext.Session.SetInt32("Masp",masp);
			ViewBag.masp = masp;

			return View(pDetail);
		}

		public void CreateData()
		{
			List<SelectListItem> MauList = mauRepo.GetMauList().Select(x=> new SelectListItem
			{
				Value = x.Mamau,
				Text = x.Tenmau
			}).ToList();
			ViewBag.MauList = MauList;
		}

        public IActionResult AddComment(int rating, string SanPhamComment)
        {
			// Kiểm tra xem người dùng đã đăng nhập hay chưa
			if (HttpContext.Session.GetString("Email") == null)
			{
				return RedirectToAction("Login", "Account");
			}

			// Lấy mã sản phẩm từ session
			int Masp = HttpContext.Session.GetInt32("Masp") ?? 0;
            // Lấy thông tin sản phẩm từ mã sản phẩm
            Sanpham sp = spRepo.Getsanpham(Masp);
            // Lấy thông tin người dùng đang đăng nhập
            string userEmail = HttpContext.Session.GetString("Email") ;
            var user = khRepo.GetCurrentKh(userEmail);

            if (user == null)
            {
                return NotFound();
            }

            // Lấy mã khách hàng
            int makh = user.Makh;

            // Kiểm tra độ dài của bình luận
           
            // Tạo đối tượng Binhluan từ thông tin đã lấy được
            Binhluan objComment = new Binhluan
            {
                Madongsanpham = sp.Madongsanpham,
                Noidungbl = SanPhamComment,
                Ngaybl = DateTime.Now,
                Makh = makh,
                Rating = rating
            };

            // Thêm bình luận vào cơ sở dữ liệu
            blRepo.AddBinhLuan(objComment);
			CommentViewModel cmtView = blRepo.GetBlList(Masp);
			return PartialView("PartialShowComment", cmtView);
        }

		public IActionResult FilterCommentPage(int page) {
			int Masp = HttpContext.Session.GetInt32("Masp") ?? 0;
			CommentViewModel cmtView = blRepo.GetBlList(Masp,page);

			return PartialView("PartialShowComment", cmtView);
		}
    }
}

ShoesStore/Views/SanPham/HienThiSanpham.cshtml
@using ShoesStore.ViewModels;
@using System.Diagnostics;
@using Newtonsoft.Json;
@model ShoesStore.ViewModels.SanphamViewModel;
@{
	string json = JsonConvert.SerializeObject(Model.slton);
	string formattedString = Model.dongsanpham.Makms.ElementAt(0)?.Ngaykt.ToString("yyyy-MM-dd");


}
@section Script{

	<script>
		var num = 0;
		function updateIndex(element, index, SizeName) {
			var h5Span = document.getElementById("sizeError");
			h5Span.style.visibility = "hidden";
			//Make error size lost

			var array = @json
								var slton = document.getElementById("slton");
			if (array[index] < 10) {
				slton.style.display = "block";

			}
			else {
				slton.style.display = "none";
			}

			var elements = document.getElementsByClassName("box-kho");
			for (var i = 0; i < elements.length; ++i) {
				elements[i].classList.remove("active");
			}
			element.classList.add("active");

			var productId = @Model.sanphams.ElementAt(0).Masp;
			var addToCartUrl = '@Url.Action("AddToCart", "ShoppingCart", new { id = "__productId__", tenSize = "__sizeName__", slton = "__slton__" })';
			addToCartUrl = addToCartUrl.replace("__productId__", productId).replace("__sizeName__", SizeName).replace("__slton__", array[index]);

			document.getElementById("AddToCart").href = addToCartUrl;

		}

		function NotChooseSize(event) {
			var addToCartLink = document.getElementById("AddToCart");

			if (addToCartLink.getAttribute("href") == "#") {
				event.preventDefault(); // prevent a tag default function

				var h5Span = document.getElementById("sizeError");
				h5Span.style.visibility = "visible";
			}

		}
		var countDownDate = new Date("@formattedString").getTime();
		var x = setInterval(function () {
			var now = new Date().getTime();
			var distance = countDownDate - now;

			var days = Math.floor(distance / (1000 * 60 * 60 * 24));
			var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
			var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
			var seconds = Math.floor((distance % (1000 * 60)) / 1000);

			document.getElementById("days").innerText = days;
			document.getElementById("hours").innerText = hours;
			document.getElementById("minutes").innerText = minutes;
			document.getElementById("seconds").innerText = seconds;
		}, 1000);



	</script>
}

<style>
	.product-images img {
		max-width: 100px; /* Adjust this value as needed */
		max-height: 100px; /* Adjust this value as needed */
		margin-right: 10px; /* Optional: Add some spacing between images */
	}

		.product-images img:hover {
			transform: scale(1.1); /* Increase size on hover */
			cursor: pointer; /* Change cursor to pointer on hover */
		}

	.box-kho {
		border: 2px solid #ccc;
		border-radius: 5px;
		padding: 8px;
		margin-bottom: 10px;
		cursor: pointer;
		color: #111111;
		font-size: 16px;
	}

		.box-kho:hover {
			border-color: #111111;
		}

		.box-kho.active {
			border-color: #111111;
		}

	.kho-disable {
		opacity: 0.5;
		pointer-events: none;
	}


</style>
<section class="banner-area organic-breadcrumb">
	<div class="container">
		<div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
			<div class="col-first">
				<h1>Product Details Page</h1>
				<nav class="d-flex align-items-center">
					<a asp-action="Index" asp-controller="Home">Home<span class="lnr lnr-arrow-right"></span></a>
					<a href="#">Shopping<span class="lnr lnr-arrow-right"></span></a>
					<a href="single-product.html">Product details</a>
				</nav>
			</div>
		</div>
	</div>
</section>
<!-- End Banner Area -->
<!--================Single Product Area =================-->
<div class="product_image_area">
	<div class="container">
		<div class="row s_product_inner">
			<div class="col-lg-6" style="display: flex; flex-direction: column;">
				<div class="s_Product_carousel" style="flex: 1;">
					<div class="single-prd-item">
						<img class="img-fluid" src="~/img/@Model.sanphams.ElementAt(0).Madongsanpham/@Model.sanphams.ElementAt(0).Anhdaidien" alt="Ảnh đại diện">
					</div>
					<div class="single-prd-item">
						<img class="img-fluid" src="~/img/@Model.sanphams.ElementAt(0).Madongsanpham/@Model.sanphams.ElementAt(0).Anhmattren" alt="Ảnh mặt trên">
					</div>
					<div class="single-prd-item">
						<img class="img-fluid" src="~/img/@Model.sanphams.ElementAt(0).Madongsanpham/@Model.sanphams.ElementAt(0).Anhdegiay" alt="Ảnh đế giày">
					</div>
					@if (!string.IsNullOrEmpty(Model.sanphams.ElementAt(0).Video))
					{
						<div class="video-wrapper">
							<video controls width="100%" height="auto">
								<source src="~/videos/@Model.sanphams.ElementAt(0).Madongsanpham/@Model.sanphams.ElementAt(0).Video" type="video/webm">
								<!-- Thêm các định dạng video khác nếu cần -->
								Your browser does not support the video tag.
							</video>
						</div>
					}
				</div>
			</div>

			<div class="col-lg-5 offset-lg-1">
				<div class="s_product_text">
					
					<h3>@Model.dongsanpham.Tendongsp</h3>
					@if (Model.dongsanpham.Makms.ElementAt(0) != null && Model.dongsanpham.Makms.ElementAt(0).Phantramgiam != 0)
					{
						decimal? priceSale = Model.dongsanpham.Giagoc - (Model.dongsanpham.Giagoc * Model.dongsanpham.Makms.ElementAt(0).Phantramgiam / 100);
						<div class="row">
							<div class="col-7">
								<h2 style="display:inline;">@(priceSale.Value.ToString("#,##0"))₫ &nbsp;</h2>
								<h5 style="display:inline;">
									<span style="text-decoration:line-through;color:#cccccc;">@(Model.dongsanpham.Giagoc.ToString("#,##0"))₫</span> &nbsp;
								</h5>
								<h5 class="mt-1" style="color:green;">@Model.dongsanpham.Makms.ElementAt(0).Phantramgiam% off</h5>
							</div>
							<div class="col-5 d-flex justify-content-center align-items-center" style="background-color: #f26921;font-weight:bold;border-radius:2px;color:white">
								<h5 style="margin: 0;color:white">
									<span id="days">00</span> :
									<span id="hours">00</span> :
									<span id="minutes">00</span> :
									<span id="seconds">00</span>
								</h5>
							</div>
						</div>

					}
					else
					{
						<h2>@Model.dongsanpham.Giagoc.ToString("#,##0")₫</h2>
					}


					<div class="product-images row mt-3" style="margin-left:auto;margin-bottom:15px">
						@foreach (Sanpham sp in Model.sanphams)
						{
							//A choosen one always the firs one with index is 0
							<a style="margin-bottom:5px" asp-action="HienThiSanpham" asp-route-madongsanpham="@Model.dongsanpham.Madongsanpham" asp-route-masp="@sp.Masp">
								<img src="~/img/@sp.Madongsanpham/@sp.Anhdaidien" alt="@Model.dongsanpham.Tendongsp">
							</a>
						}
					</div>

					<div id="slton" style="display:none;">
						<h5 style="color: #BA861E;">
							<i class="fas fa-clock" style="color: #BA861E;"></i> Just a few left. Order soon!
						</h5>
					</div>


					<div class="row" style="margin-top: 5px;margin-bottom:5px;">
						<div class="col-12 ">
							<h5 class="text-left">Table Size</h5>
						</div>
						@for (int tkho = 0; tkho < Model.tenSize.Count(); ++tkho)
						{

							<div class="col-lg-3 col-md-4 col-sm-6 " style="max-width: 80px; max-height:50px">
								@{
									string boxClass = Model.slton[tkho] > 0 ? "box-kho" : "box-kho kho-disable disabled";
									string onClick = Model.slton[tkho] > 0 ? $"updateIndex(this,{tkho},{Model.tenSize[tkho]})" : "";
								}
								<div class="@boxClass text-center" onclick="@onClick">
									@Model.tenSize[tkho]
								</div>
							</div>


						}
						<div class="col-12 ">
							<h5 class="text-left" id="sizeError" style="color:red;visibility:hidden">Please choose size</h5>
						</div>
					</div>

					<div class="card_area d-flex align-items-center">
						<a id="AddToCart" class="primary-btn" onclick="NotChooseSize(event)" href="#">Add to Cart</a>
						<a class="icon_btn" asp-action="AddFavouriteProducts" asp-controller="FavouriteProducts" asp-route-id="@ViewBag.masp">
							<i class="lnr lnr-heart"></i>
						</a>
					</div>
				</div>

			</div>
		</div>
	</div>
</div>
<!--================End Single Product Area =================-->

<section class="product_description_area">
	<div class="container">
		<ul class="nav nav-tabs" id="myTab" role="tablist">
			<li class="nav-item">
				<a class="nav-link" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Description</a>
			</li>
			<li class="nav-item">
				<a class="nav-link active" id="review-tab" data-toggle="tab" href="#review" role="tab" aria-controls="review"
				   aria-selected="false">Reviews</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" id="sizes-tab" data-toggle="tab" href="#sizes" role="tab" aria-controls="sizes" aria-selected="false">Sizes Table</a>
			</li>
		</ul>
		<div class="tab-content" id="myTabContent">
			<div class="tab-pane fade" id="home" role="tabpanel" aria-labelledby="home-tab">
				<p>
					@Model.dongsanpham.Mota;
				</p>
			</div>
			
	
			<div class="tab-pane fade show active" id="review" role="tabpanel" aria-labelledby="review-tab">
				<div class="row">
					@await Component.InvokeAsync("ShowComment")
				</div>
			</div>
			<div class="tab-pane fade" id="sizes" role="tabpanel" aria-labelledby="sizes-tab">
				<div class="row">
					<img src="~/img/size/sizes.jpg" style="width: 50%; height: auto; display: block; margin: 0 auto;">
				</div>
			</div>
		</div>
	</div>
</section>

@await Component.InvokeAsync("HomeProductSlider2",new {trangthai =4});

ShoesStore/Views/SanPham/SanPhamTheoLoai.cshtml
@using System.Diagnostics;
@using X.PagedList.Mvc.Core;
@using ShoesStore.ViewModels;
@model List<DongsanphamViewModel>

<style>

	.product-images img {
		max-width: 50px; /* Adjust this value as needed */
		max-height: 50px; /* Adjust this value as needed */
		margin-right: 10px; /* Optional: Add some spacing between images */
	}

		.product-images img:hover {
			transform: scale(1.1); /* Increase size on hover */
			cursor: pointer; /* Change cursor to pointer on hover */
		}

	.product-details {
		opacity: 1;
		transition: opacity 0.8s ease-in;
	}

		.product-details.lost {
			display: none;
			opacity: 0;
		}

	.product-images.hidden {
		display: none;
	}


</style>
@section Script{
	<script>
		var maMau1 = '@ViewBag.maMau1';
		var maLoai1 = '@ViewBag.maLoai';
		var searchString1 = '@ViewBag.searchString1';
		var sortGia1 = '@ViewBag.sortGia1';
		var minPrice1 = '@ViewBag.minPrice1';
		var maxPrice1 = '@ViewBag.maxPrice1';

		$(document).ready(function () {
			$('#sortGia').change(function () {
				var selectedValue = $(this).val();

				if (selectedValue) {
					sortGia1 = selectedValue;
					getToController();
				}
			});
			$('.pixel-radio.mauInput').click(function () {
				var selectedValue = $(this).attr('value');
				var isSelected = $(this).hasClass('selected');
				
				if (isSelected) {
					$(this).css({
						'border': 'none',
					});
					maMau1 = '';
					$(this).removeClass('selected');
				} else {
					$('.pixel-radio.mauInput').css({
						'border': 'none',
					});
					$('.pixel-radio.mauInput').removeClass('selected');
					$(this).css({
						'border': '5px solid #FFBA00',
						'box-sizing':'border-box',
						
					});
					maMau1 = selectedValue;
					$(this).addClass('selected');
				}
				getToController();
			});

			
			$('#search_input').val(searchString1);

			var priceRange = document.getElementById("price-range2");
			var lowerValue = document.getElementById("lower-value2");
			var upperValue = document.getElementById("upper-value2");

			var minPrice = 0;
			var maxPrice = 10000000;
			var lowerBound = 0;
			var upperBound = 10000000;

			lowerValue.textContent = lowerBound;
			upperValue.textContent = upperBound;

			noUiSlider.create(priceRange, {
				start: [lowerBound, upperBound],
				connect: true,
				range: {
					'min': minPrice,
					'max': maxPrice
				},
				step: 500000,
			});

			priceRange.noUiSlider.on('update', function (values, handle) {
				var value = values[handle];
				if (handle == 0) {
					lowerValue.innerText = formatPrice(Math.round(value));
				}
				else {
					upperValue.innerText = formatPrice(Math.round(value));
				}
				minPrice1 = values[0];
				maxPrice1 = values[1];
				getToController();
			});

			function formatPrice(price) {
				return price.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ".");
			}

			function getToController() {
				console.log("Get to controller: ");
				$.ajax({
					url: '/SanPham/SanPhamTheoLoai',
					type: 'Get',
					data: {
						page: null,
						searchString: searchString1,
						maMau: maMau1,
						sortGia: sortGia1,
						minPrice: minPrice1,
						maxPrice: maxPrice1,
						maLoai: maLoai1
					},
					success: function (response) {
						$('.lattest-product-area .row').html(response);

						
						
					},
				});
			}
		});

		function showProductDetails(element) {
			var productDetails = element.querySelector('.product-details');
			productDetails.classList.toggle('lost');

			var productImages = element.querySelector('.product-images');
			productImages.classList.toggle('hidden');
		}


	</script>
 }


<section class="banner-area organic-breadcrumb mb-5">
	<div class="container">
		<div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
			<div class="col-first">
				<h1>Shop Category page</h1>
				<nav class="d-flex align-items-center">
					<a asp-action="Index" asp-controller="Home">Home<span class="lnr lnr-arrow-right"></span></a>
					<a href="#">Shopping<span class="lnr lnr-arrow-right"></span></a>
					<a href="#">Running</a>
				</nav>
			</div>
		</div>
	</div>
</section>
<!-- End Banner Area -->
<div class="container" id="content">
	<div class="row">
		<div class="col-xl-3 col-lg-4 col-md-5">
			<div class="sidebar-filter mt-0">
				<form asp-action="SanPhamList" asp-controller="SanPham" id="form-search">
					<div class="top-filter-head">Filter Products</div>
					<div class="common-filter">
						<div class="head">Colors</div>
						<ul>
							@foreach (SelectListItem mau in ViewBag.MauList)
							{
								<li class="filter-list">
									
									<input class="pixel-radio mauInput" type="radio" name="color" style="background-color:@mau.Value"
									value="@mau.Value">
									<label>
										@mau.Text
									</label>
								</li>
							}
						</ul>
					</div>
					<div class="common-filter">
						<div class="head">Price</div>
						<div class="price-range-area">
							<div id="price-range2"></div>
							<div class="value-wrapper d-flex">
								<div class="price">Price from:</div>
								<div id="lower-value2"></div>
								<span>₫</span>
								<div class="to"> - </div>
								<div id="upper-value2"></div>
								<span>₫</span>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
		<div class="col-xl-9 col-lg-8 col-md-7">
			<!-- Start Filter Bar -->
			<div class="filter-bar d-flex flex-wrap align-items-center">
				<div class="sorting">
					<select id="sortGia" name="sortGia">
						<option value="0">Sort Price</option>
						<option value="1">Price ascending</option>
						<option value="2">Price descending</option>
					</select>
				</div>
				
			</div>
			<!-- End Filter Bar -->
			<!-- Start Best Seller -->

			<section class="lattest-product-area pb-40 category-list">
				<div class="row">
					<partial name="_PartialSanPhamTheoLoai" model="@Model" />
				</div>
			</section>

			<!-- End Best Seller -->
			<!-- Start Filter Bar -->
			<!-- End Filter Bar -->
		</div>
	</div>
</div>

@await Component.InvokeAsync("BlogLast",new {theloai = "Thumbnail"});