ShoesStore/Areas/Admin/Controllers/StaffAdminController.cs
using Microsoft.AspNetCore.Mvc;
using ShoesStore.Areas.Admin.ViewModels;
using ShoesStore.Models;
using ShoesStore.Models.Authentication;
using System.Diagnostics;
using System.Linq;

namespace ShoesStore.Areas.Admin.Controllers
{
	[Area("Admin")]
    [AuthenticationAdmin]

    public class StaffAdminController : Controller
	{
		private readonly ShoesDbContext _db;


		public StaffAdminController(ShoesDbContext db)
		{
			_db = db;
		}
		[HttpGet]
		public IActionResult ListEmployees()
		{
			// Lấy danh sách tất cả nhân viên từ cơ sở dữ liệu
			//var employees = _db.Nhanviens.ToList();

			return View(_db.Nhanviens.ToList());
		}
		public IActionResult CreateEmployee()
		{
			return View();
		}

		[HttpPost]
		public IActionResult CreateEmployee(RegisterAdminViewModel rgAdmin)
		{
			Taikhoan newTk = new Taikhoan
			{
				Email = rgAdmin.Nhanvien.Email,
				Matkhau = rgAdmin.Taikhoan.Matkhau,
				Loaitk = 1
			};
			rgAdmin.Taikhoan = newTk;
			rgAdmin.Nhanvien.EmailNavigation.Email = rgAdmin.Nhanvien.Email;
			rgAdmin.Nhanvien.EmailNavigation.Loaitk = 1;

            rgAdmin.Nhanvien.Diachi = rgAdmin.Nhanvien.Diachi == "123" ? "" : rgAdmin.Nhanvien.Diachi;
			//If use modelstate.isvalid need to make input for emailnavigation in create view
			//But we have already use view model

			// Kiểm tra xem đã có tài khoản với email này chưa
			var existingEmployee = _db.Taikhoans.FirstOrDefault(c => c.Email == rgAdmin.Taikhoan.Email);

			if (existingEmployee != null)
			{
				// Trả về thông báo lỗi nếu email đã tồn tại
				ModelState.AddModelError("Nhanvien.Email", "Email already exists.");
				return View(rgAdmin);
			}
			if (!ModelState.IsValid)
			{
				return View(rgAdmin);
			}

			_db.Nhanviens.Add(rgAdmin.Nhanvien);
			_db.SaveChanges();

			// Chuyển hướng đến trang quản lý nhân viên hoặc trang chính của ứng dụng
			return RedirectToAction("ListEmployees");
		}
		// Cập nhật nhân viên (Hiển thị form cập nhật)
		[HttpGet]
		public IActionResult EditEmployee(int id)
		{
			//Check xem email có phải email đã dùng chưa , nếu là email cũ của chính nhân viên đó thì accept
			//Còn email trùng với email của nhân viên khác thì từ chối
			//Chỉnh email bên nhân viên thì cũng chỉnh email bên tài khoản
			// Tìm nhân viên cần cập nhật trong cơ sở dữ liệu
			var employee = _db.Nhanviens.Find(id);
			employee.EmailNavigation = _db.Taikhoans.Find(employee.Email);

			if (employee == null)
			{
				return NotFound();
			}

			return View(employee);
		}

		// Xử lý cập nhật nhân viên (POST)
		[HttpPost]
		public IActionResult EditEmployee(Nhanvien employee)
		{
			if (ModelState.IsValid)
			{
				_db.Nhanviens.Update(employee);
				_db.SaveChanges();

				return RedirectToAction("ListEmployees");
			}

			return View(employee);
		}

		// Xóa nhân viên
		[HttpPost]
		public IActionResult DeleteEmployee(int id)
		{
			//Thêm filed kích hoạt tài khoản 
			//Nếu nhân viên nghỉ thì không kích hoạt tài khoản

			var employee = _db.Nhanviens.Find(id);

			if (employee == null)
			{
				return NotFound();
			}

			_db.Nhanviens.Remove(employee);
			_db.SaveChanges();

			return RedirectToAction("ListEmployees");
		}
	}
}

ShoesStore/Areas/Admin/Views/StaffAdmin/CreateEmployee.cshtml
@model ShoesStore.Areas.Admin.ViewModels.RegisterAdminViewModel

<div class="text-center">
    <h2 class="display-4">Add Employee</h2>
</div>

<div class="col-lg-6">
    <div class="login_form_inner">
        <form asp-action="CreateEmployee" asp-controller="StaffAdmin" class="row login_form" method="post" id="contactForm" novalidate="novalidate">
            <input asp-for="@Model.Taikhoan.Email" value="123" hidden />
            <input asp-for="@Model.Nhanvien.EmailNavigation.Email" value="123" hidden />
            <input asp-for="@Model.Nhanvien.EmailNavigation.Matkhau" value="123456" hidden />
            <div class="col-md-12 form-group">
                <label asp-for="@Model.Nhanvien.Tennv">Employee Name <span style="color:red">*</span> : </label>
                <input asp-for="@Model.Nhanvien.Tennv" type="text" class="form-control" placeholder="Họ và Tên" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Tên tài khoản'">
                <span class="text-danger text-left" style="text-align:left;">@Html.ValidationMessageFor(model => model.Nhanvien.Tennv)</span>
            </div>
            <div class="col-md-12 form-group">
                <label asp-for="@Model.Nhanvien.Email">Email <span style="color:red">*</span> : </label>
                <input asp-for="@Model.Nhanvien.Email" type="email" class="form-control" placeholder="Email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email'">
                <span class="text-danger text-left" style="text-align:left;">@Html.ValidationMessageFor(model => model.Nhanvien.Email)</span>
            </div>
            <div class="col-md-12 form-group">
                <label asp-for="@Model.Taikhoan.Matkhau">Password <span style="color:red">*</span> : </label>
                <input asp-for="@Model.Taikhoan.Matkhau" type="text" class="form-control" value="123456" readonly>
            </div>
            <div class="col-md-12 form-group">
                <label asp-for="@Model.Nhanvien.Diachi">Address : </label>
                <input asp-for="@Model.Nhanvien.Diachi" type="text" class="form-control" placeholder="Địa chỉ" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Địa chỉ'">
            </div>

            <div class="col-md-12 form-group">
                <label asp-for="@Model.Nhanvien.Sdt">Phone number <span style="color:red">*</span> : </label>
                <input asp-for="@Model.Nhanvien.Sdt" type="text" class="form-control" placeholder="Số điện thoại" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Số điện thoại'" required>
                <span class="text-danger text-left" style="text-align:left;">@Html.ValidationMessageFor(model => model.Nhanvien.Sdt)</span>
            </div>

            <div class="col-md-12 form-group">
                <label asp-for="@Model.Nhanvien.Gioitinh">Gender <span style="color:red">*</span> : </label>
                <select asp-for="@Model.Nhanvien.Gioitinh" class="form-control" required>
                    <option value="">Chọn giới tính</option>
                    <option value="true">Nam</option>
                    <option value="false">Nữ</option>
                </select>
                <span class="text-danger" style="text-align:left;">@Html.ValidationMessageFor(model => model.Nhanvien.Gioitinh)</span>
            </div>

            <div class="col-md-12 form-group">
                <label asp-for="@Model.Nhanvien.Ngaysinh">Birth <span style="color:red">*</span> : </label>
                <input asp-for="@Model.Nhanvien.Ngaysinh" type="date" class="form-control" placeholder="Ngày sinh" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Ngày sinh'" required>
                <span class="text-danger" style="text-align:left;">@Html.ValidationMessageFor(model => model.Nhanvien.Ngaysinh)</span>
            </div>

            <div class="col-md-12 form-group">
                <button type="submit" value="submit" class="primary-btn">Add</button>
            </div>
        </form>



    </div>
</div>

ShoesStore/Areas/Admin/Views/StaffAdmin/EditEmployee.cshtml
@model ShoesStore.Models.Nhanvien

<div class="text-center">
    <h2 class="display-4">Edit Employee</h2>
</div>

<div class="col-lg-6">
    <div class="login_form_inner">
        <form asp-action="EditEmployee" asp-controller="StaffAdmin" class="row login_form" method="post" id="contactForm" novalidate="novalidate">
            <input type="hidden" asp-for="@Model.Manv" />
            <input asp-for="@Model.EmailNavigation.Matkhau" hidden />
            <input  asp-for="@Model.EmailNavigation.Email" hidden/>
            <input asp-for="@Model.EmailNavigation.Loaitk" hidden/>
            <div class="col-md-12 form-group">
                <label asp-for="@Model.Tennv">Employee name <span style="color:red">*</span> : </label>
                <input asp-for="@Model.Tennv" type="text" class="form-control" placeholder="Họ và Tên" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Tên tài khoản'" value="@Model.Tennv">
                <span class="text-danger text-left" style="text-align:left;">@Html.ValidationMessageFor(model => model.Tennv)</span>
            </div>
            <div class="col-md-12 form-group">
                <label asp-for="@Model.Email">Email <span style="color:red">*</span> : </label>
                <input asp-for="@Model.Email" type="email" class="form-control" placeholder="Email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email'" value="@Model.Email">
                <span class="text-danger text-left" style="text-align:left;">@Html.ValidationMessageFor(model => model.Email)</span>
            </div>
            <div class="col-md-12 form-group">
                <label asp-for="@Model.Diachi">Address : </label>
                <input asp-for="@Model.Diachi" type="text" class="form-control" placeholder="Địa chỉ" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Địa chỉ'" value="@Model.Diachi">
            </div>

            <div class="col-md-12 form-group">
                <label asp-for="@Model.Sdt">Phone number <span style="color:red">*</span> : </label>
                <input asp-for="@Model.Sdt" type="text" class="form-control" placeholder="Số điện thoại" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Số điện thoại'" required value="@Model.Sdt">
                <span class="text-danger text-left" style="text-align:left;">@Html.ValidationMessageFor(model => model.Sdt)</span>
            </div>

            <div class="col-md-12 form-group">
                <label asp-for="@Model.Gioitinh">Gender <span style="color:red">*</span> : </label>
                <select asp-for="@Model.Gioitinh" class="form-control" required>
                    <option value="">Chọn giới tính</option>
                    <option value="true" selected="@Model.Gioitinh">Nam</option>
                    <option value="false" selected="@(!Model.Gioitinh)">Nữ</option>
                </select>
                <span class="text-danger" style="text-align:left;">@Html.ValidationMessageFor(model => model.Gioitinh)</span>
            </div>

            <div class="col-md-12 form-group">
                <label asp-for="@Model.Ngaysinh">Birth <span style="color:red">*</span> : </label>
                <input asp-for="@Model.Ngaysinh" type="date" class="form-control" placeholder="Ngày sinh" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Ngày sinh'" required value="@Model.Ngaysinh">
                <span class="text-danger" style="text-align:left;">@Html.ValidationMessageFor(model => model.Ngaysinh)</span>
            </div>

            <div class="col-md-12 form-group">
                <button type="submit" value="submit" class="primary-btn">Edit</button>
            </div>
        </form>
    </div>
</div>

ShoesStore/Areas/Admin/Views/StaffAdmin/ListEmployees.cshtml
@using ShoesStore.Models
@model IEnumerable<Nhanvien>

<!--Just show data of nhan vien, just show password in update because it not frequently data used-->
<a asp-action="CreateEmployee" class="btn btn-primary">Add Employee</a>
<div class="container">
    <h2 class="text-center">List of Employees</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Birth</th>
                <th>Gender</th>
                <th>Phone number</th>
                <th>Email</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var employee in Model)
            {
                <tr>
                    <td>@employee.Tennv</td>
                    <td>@employee.Ngaysinh</td>
                    <td>@(employee.Gioitinh ? "Nam" : "Nữ")</td>
                    <td>@employee.Sdt</td>
                    <td>@employee.Email</td>
                    <td>
                        <form asp-controller="StaffAdmin" asp-action="EditEmployee" method="get">
                            <input type="hidden" name="id" value="@employee.Manv" />
                            <button type="submit" class="btn btn-primary btn-sm">
                                <i class="fas fa-pen"></i>
                            </button>
                        </form>
                        <form asp-controller="StaffAdmin" asp-action="DeleteEmployee" method="post">
                            <input type="hidden" name="id" value="@employee.Manv" />
                            <button type="submit" class="btn btn-danger btn-sm">
                                <i class="fas fa-trash-alt"></i>
                            </button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>