ShoesStore/Models/Loai.cs
using System;
using System.Collections.Generic;

namespace ShoesStore.Models;

public partial class Loai
{
    public int Maloai { get; set; }

    public string Tenloai { get; set; } = null!;

    public virtual ICollection<Dongsanpham> Dongsanphams { get; set; } = new List<Dongsanpham>();
}

ShoesStore/Areas/Admin/Controllers/LoaiController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShoesStore.Areas.Admin.InterfaceRepositories;
using ShoesStore.Models;
using ShoesStore.Models.Authentication;
using ShoesStore.ViewModels;

namespace ShoesStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    [AuthenticationM_S]
    public class LoaiController : Controller
    {

        private readonly ILoaiAdmin _lrepo;
        public LoaiController(ILoaiAdmin lrepo)
        {
            _lrepo = lrepo;
        }
        public IActionResult Index()
        {
            return View(_lrepo.GetAllLoai().ToList());
        }

        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]

        public IActionResult Create([Bind("Idloai,Tenloai,Slogan")] Loai loai)
        {
            if (!ModelState.IsValid)
            {
                return View(loai);
            }

            _lrepo.AddLoai(loai);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int Id)
        {
            Loai loai = _lrepo.GetLoaiById(Id);
            return View(loai);
        }


        [HttpPost]
        public IActionResult Edit(Loai loai, int Id)
        {
            if (!ModelState.IsValid)
            {
                return View(loai);
            }

            _lrepo.UpdateLoai(loai, Id);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            _lrepo.DeleteLoai(id);
            return RedirectToAction("Index");
        }

    }
}

ShoesStore/Areas/Admin/Views/Loai/Create.cshtml
@model ShoesStore.Models.Loai

@{
    ViewData["Title"] = "Create";
}

@using (Html.BeginForm("Create", "Loai", FormMethod.Post, new { }))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h2 class="card-center">Create New Shoes Category </h2>
                <form class="forms-sample">
                    <div class="form-group">
                        <label>Shoes Category Name</label>
                        <input type="text" asp-for="Tenloai" class="form-control" id="exampleInputName1" placeholder="Name">
                    </div>                  
                    <button type="submit" class="btn btn-gradient-primary me-2">Create</button>
                    <a href="@Url.Action("Index", "Loai")" class="btn btn-light">Cancel</a>
                </form>
            </div>
        </div>
    </div>   
}

ShoesStore/Areas/Admin/Views/Loai/Edit.cshtml
@model ShoesStore.Models.Loai

@{
    ViewData["Title"] = "Edit";
}

@using (Html.BeginForm("Edit", "Loai", FormMethod.Post, new { }))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h2 class="card-center">Edit Shoes Category</h2>
                <form class="forms-sample">
                    <div class="form-group">
                        <label asp-for="Tenloai">Shoes Category Name</label>
                        <input type="text" asp-for="Tenloai" class="form-control" id="exampleInputName1" placeholder="Name">
                        <span asp-validation-for="Tenloai" class="text-danger"></span>
                    </div>
                    <button type="submit" class="btn btn-gradient-primary me-2">Edit</button>
                    <a href="@Url.Action("Index", "Loai")" class="btn btn-light">Cancel</a>
                </form>
            </div>
        </div>
    </div>
}

ShoesStore/Areas/Admin/Views/Loai/Index.cshtml
@using ShoesStore.Models
@model List<Loai>
@{
    ViewData["title"] = "Type page";
}

<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet">

<link rel="stylesheet" href="path/to/font-awesome/css/all.min.css" />

<div class="text-center">
    <h2 class="display-4">SHOES CATEGORY LIST</h2>
</div>

@section searchArea{
    <form id="searchForm" asp-controller="Loai" asp-action="Index" method="get" class="d-flex" style="width:468px">
        <div class="input-group">
            <!-- Search bar -->
            <input name="searchString" id="searchString" type="search" placeholder="search type shoes..." class="form-control rounded" aria-label="Search" style="width:100px">
            <button class="btn btn-info rounded" type="submit" style="width: 40px; height: 40px;">
                <i class="fas fa-search"></i>
            </button>
        </div>
    </form>

}
<div style="display: flex; justify-content: space-between; align-items: center; width:100%">
    <!-- Link for creating a new Loai -->
    <a asp-action="Create" asp-controller="Loai" class="btn btn-primary"><i class="mdi mdi-plus-circle"></i></a>
</div>
<div class="table-responsive">
    <table class="table table-striped table-bordered text-center">
        <thead>
            <tr>
                <th scope="col">Index</th>
                <th scope="col">Shoes Category Name</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            <!-- Populate table with Loai data -->
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Maloai</td>
                    <td>@item.Tenloai</td>        
                    <td>
                        <a asp-action="Edit" asp-controller="Loai" asp-route-id="@item.Maloai" class="btn btn-gradient-primary">
                            <i class="mdi mdi-table-edit"></i>
                        </a>
                        <form asp-controller="Loai" asp-action="Delete" asp-route-id="@item.Maloai" method="post" class="d-inline">
                            <button type="submit" class="btn btn-gradient-danger">
                                <i class="mdi mdi-delete"></i>
                            </button>
                        </form>
                    </td>

                </tr>
            }
        </tbody>
    </table>
</div>